# Generated by Django 3.2.15 on 2022-08-27 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('category', models.CharField(choices=[('Samsung s22 ultra', 'Samsung s22 ultra'), ('Samsung Galaxy Tab', 'Samsung Galaxy Tab'), ('SAMSUNG 55QN700B 55', 'SAMSUNG 55QN700B 55'), ('Galaxy Watch4 Classic', 'Galaxy Watch4 Classic')], max_length=30, verbose_name='Категория')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_reviews', models.TextField(max_length=3000, verbose_name='Отзыв')),
                ('grade', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('moderated', models.BooleanField(default=True, verbose_name='Промодерировать')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webapp.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
