# Generated by Django 3.2.15 on 2022-09-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Промодерировать'),
        ),
    ]
